### ISSUE TITLE
includePaths throws linting error

### ISSUE THREAD

**Issue by alexander-patton** [ionic-team/stencil-sass#14]
```
plugins: [
    sass({includePaths: ["node_modules"]})
  ]
```
The code compiles and runs fine, but gives this linting error in VS Code...

Argument of type '{ includePaths: string[]; }' is not assignable to parameter of type 'PluginOptions'.
  Object literal may only specify known properties, and 'includePaths' does not exist in type 'PluginOptions'. [2345]

**Comment by chris-dura** [comment]
I'm not sure if it's the proper solution, but I think so... the `PluginOptions` type extends the `Options` type from `node-sass`, so if you `npm install @types/node-sass` then VS Code should stop throwing an error (because it now knows that `Options` has an `includePaths` prop).

**Comment by codef0rmer** [comment]
This works. The issue should now be closed.
