### ISSUE TITLE
Use sass in styles property (component decorator)

### ISSUE THREAD

**Issue by KenavR** [ionic-team/stencil-sass#16]
Not sure if this is the right place to ask this, but is it possible to use sass/scss inside the styles property of the decorator?

I like keeping components in a single file, but I also would like to use scss. 

**Example**

```js
@Component({
  tag: 'my-hero',
  styles: `
    .hero {
      ...
      &__details {
        ...
      }

      &__screenshot {
        ...
      }
    }
  `,
  shadow: true
})
export class Hero {
  render() {
    return (
        <div class="hero">
          <div class="hero__details">
            ...
          </div>
          <div class="hero__screenshot">
            ...
          </div>
        </div>
    );
  }
}
```

thanks.

**Comment by splitinfinities** [comment]
You know, that's a good question. I'm not so sure it is. Would you like this behavior? If so, upvote this please! 

Also, it may be worth signal boosting this more so in the @ionic-team/stencil repo. That way, other non-sass community users could benefit from this behavior as well, if we decide to introduce it. Ultimately, that's where the code change would probably be anyways.

**Comment by rwaskiewicz** [comment]
Hey! Thanks for this suggestion!

I don't think we've received enough signal from the community that this feature is desired. As a result, I'm going to close this for now. We can always re-evaluate this feature request some time in the future.

Thanks again!
