### ISSUE TITLE
Support of Stencil 2.0

### ISSUE THREAD

**Issue by jwillmer** [ionic-team/stencil-sass#38]
Are were plans to support Stencil 2.0 and when would that be? We can't migrate our projects to Stencil 2.x since `stencil-sass` does not support it.

**Comment by claviska** [comment]
What issue are you facing with Stencil 2 and `@stencil/sass`? I've been successfully using this combination for awhile and everything is working as expected for me.

Was this just an assumption that they don't work together?

**Comment by claviska** [comment]
I've confirmed with multiple others in the Stencil Slack group that this is working for them as well. 😅

I'm closing this because it's leading to confusion, as folks are assuming it doesn't work. If there's a reproducible problem, free free to comment here and we'll reopen.

**Comment by bjolletz** [comment]
I think I've found what the issue was for me, perhaps it can help others with the same problem.

I was using the `styleUrls` property because I had assumed this property would allow me to specify a list os scss files. This apparently worked prior to Stencil 2.0. But looking closer at the documentation, `styleUrls`  is actually described as "Similar as `styleUrl` but allows to specify different stylesheets for different modes." So this is apparently not expected to just be a list of CSS/SCSS files. It's not documented though what exactly it should contain which is a bit unfortunate. But apparently it doesn't work to list a bunch of scss files there anymore.

When I changed my code to use the `styleUrl` property instead, it works.

**Comment by cam-narzt** [comment]
@claviska how are you testing this? It doesn't work at all:
```
$ npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend@0.0.1
npm ERR! Found: @stencil/core@2.2.0
npm ERR! node_modules/@stencil/core
npm ERR!   dev @stencil/core@">=2.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @stencil/core@"^1.0.2" from @stencil/sass@1.3.2
npm ERR! node_modules/@stencil/sass
npm ERR!   dev @stencil/sass@">=1.3.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/camdennarzt/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/camdennarzt/.npm/_logs/2020-10-28T19_35_10_781Z-debug.log
```

**Comment by claviska** [comment]
It's alive and well in two projects I maintain. The public one can be found here: https://github.com/shoelace-style/shoelace/blob/next/package.json#L43

> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps

It looks like `@stencil/core` is a peer dependency, and the way those get installed by npm changed in npm 7, so you probably need to install core manually:

```bash
npm install -D @stencil/core
```

Or use the `--legacy-peer-deps` flag as [discussed here](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major#peer-dependencies).

**Comment by cam-narzt** [comment]
I have `@stencil/core` already installed and added to my `package.json`, the problem is that `@stencil/sass` requires you to use stencil 1, right here: https://github.com/ionic-team/stencil-sass/blob/master/package.json#L22

The dep should use a `>=` or something.

**Comment by claviska** [comment]
Fair enough, I'll look into getting that updated and hopefully that will solve it for those having trouble.

I still can't replicate this, though, so a step-by-step would be helpful. I just tried a fresh project:

1. `npm init stencil`
2. `cd [project]`
3. `npm install`
4. `npm install -D @stencil/sass`
5. [Follow these instructions to configure Sass](https://github.com/ionic-team/stencil-sass#stencilsass)
6. Change `my-component.css` to `my-component.scss`
7. Add a Sass-specific syntax and save

**Comment by cam-narzt** [comment]
Here's what I get following those steps with node: `v15.0.1`:
```
camdennarzt@WALLE:/tmp $ npm init stencil
Need to install the following packages:
  create-stencil
Ok to proceed? (y) y

✔ Pick a starter › app
✔ Project name › blah

✔ All setup  in 20 ms

  $ npm start
    Starts the development server.

  $ npm run build
    Builds your components/app in production mode.

  $ npm test
    Starts the test runner.


  We suggest that you begin by typing:

   $ cd blah
   $ npm install
   $ npm start

  Further reading:

   - https://github.com/ionic-team/stencil-app-starter

  Happy coding! 🎈

camdennarzt@WALLE:/tmp $ cd blah/
camdennarzt@WALLE:/tmp/blah $ npm install

added 3 packages, and audited 3 packages in 1s

found 0 vulnerabilities
camdennarzt@WALLE:/tmp/blah $ cat package.json 
{
  "name": "blah",
  "private": true,
  "version": "0.0.1",
  "description": "Stencil App Starter",
  "scripts": {
    "build": "stencil build",
    "start": "stencil build --dev --watch --serve",
    "test": "stencil test --spec --e2e",
    "test.watch": "stencil test --spec --e2e --watchAll",
    "generate": "stencil generate"
  },
  "devDependencies": {
    "@stencil/core": "^2.0.0",
    "@stencil/router": "^1.0.1"
  },
  "license": "MIT"
}
camdennarzt@WALLE:/tmp/blah $ npm install -D @stencil/sass
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: blah@0.0.1
npm ERR! Found: @stencil/core@2.2.0
npm ERR! node_modules/@stencil/core
npm ERR!   dev @stencil/core@"^2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @stencil/core@"^1.0.2" from @stencil/sass@1.3.2
npm ERR! node_modules/@stencil/sass
npm ERR!   dev @stencil/sass@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/camdennarzt/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/camdennarzt/.npm/_logs/2020-10-28T20_01_49_683Z-debug.log
```

**Comment by claviska** [comment]
This is starting to make sense now 🙃 

Node 15 is throwing that error. If you're on <=14 you won't see it, so things just "work." I'll work on a fix. Thanks for providing the extra details!

**Comment by prodrammer** [comment]
FYI, I get a similar error on node 16. Downgrading to 14 fixed it.
