### ISSUE TITLE
v1.4.0 breaks mixins included via injectGlobalPaths

### ISSUE THREAD

**Issue by nikrolls** [ionic-team/stencil-sass#43]
Something about the upgrade from v1.3.2 to v1.4.0 has broken the ability to have global mixins declared in `injectGlobalPaths` files accessible to any other `scss` files in the project. 

Here is a minimal reproduction of the issue: https://github.com/nikrolls/stenciljs-sass-globalpaths-repro

```
$ npm start

> stenciljs-sass-globalpaths-repro@0.0.1 start
> stencil build --dev --watch --serve

[34:03.0]  @stencil/core
[34:03.2]  v1.17.4 🏏
[34:07.8]  build, stenciljs-sass-globalpaths-repro, dev mode, started ...
[34:07.9]  transpile started ...
[34:10.2]  transpile finished in 2.30 s
[34:10.2]  copy started ...
[34:10.2]  generate lazy started ...
[34:10.2]  copy finished (0 files) in 39 ms
[34:10.9]  generate lazy finished in 753 ms

[ ERROR ]  sass error: src/global/global.scss:1:72
           Undefined mixin.

      L1:  @include test-mixin;

[34:10.9]  build failed, watching for changes... in 3.12 s
```
However, if you change `@stencil/sass` in `package.json` to `1.3.2`:
```
$ npm upgrade

changed 1 package, and audited 3 packages in 2s

found 0 vulnerabilities
$ npm start

> stenciljs-sass-globalpaths-repro@0.0.1 start
> stencil build --dev --watch --serve

[35:42.3]  @stencil/core
[35:42.5]  v1.17.4 🏏
[35:47.1]  build, stenciljs-sass-globalpaths-repro, dev mode, started ...
[35:47.1]  transpile started ...
[35:49.7]  transpile finished in 2.53 s
[35:49.7]  copy started ...
[35:49.7]  generate lazy started ...
[35:49.7]  copy finished (0 files) in 71 ms
[35:50.6]  generate lazy finished in 888 ms
[35:50.6]  build finished, watching for changes... in 3.47 s
```
Everything works fine.

This simple repro only demonstrates the issue in `globalStyle`, however it affects component `scss` files as well.

This is also an issue in Stencil 2, but I kept it on Stencil 1 because `@stencil/sass` v1.3.2 doesn't support Stencil 2 and I wanted to keep the changes between scenarios to a minimum.

**Comment by SheepFromHeaven** [comment]
@nikrolls I encountered the same problem.
The issue behind our problem is the change that has been done using `@use` instead of `@import`.

**Comment by driskull** [comment]
We are seeing the same issue

**Comment by SheepFromHeaven** [comment]
@adamdbradley I will fix it by extending the injectGlobalPaths options to being able to choose the way of importing (import vs use) with the default being import, so the package will not get breaking version and we all can work on without upgrading all our settings.

**Comment by SheepFromHeaven** [comment]
I just noticed, the docs even say v2 but it has been released as v1.4

**Comment by erichstark** [comment]
I have got an error that variables (from injectGlobalPath) are not available in components. Any tips how to solve it?

```
[ ERROR ]  sass error: src/components/tooltip/tooltip.scss:27:23
           Undefined variable.

     L26:  .tippy-box {
     L27:    background-color: $color--success;
     L28:  }
```

**Comment by dutscher** [comment]
@jaredcbaum you wrote in the readme for version 2 but the release was 1.4.0 :)

**Comment by jaredcbaum** [comment]
@dutscher Yep, you're right.  The changes have been reverted in v1.4.1.  Those changes will be rereleased in v2 like the docs said previously, since they are breaking changes.

**Comment by jaredcbaum** [comment]
> I have got an error that variables (from injectGlobalPath) are not available in components. Any tips how to solve it?
> 
> ```
> [ ERROR ]  sass error: src/components/tooltip/tooltip.scss:27:23
>            Undefined variable.
> 
>      L26:  .tippy-box {
>      L27:    background-color: $color--success;
>      L28:  }
> ```

Updating to stencil-sass v1.4.1 or downgrading to v1.3.2 should fix.

**Comment by jaredcbaum** [comment]
@erichstark Upgrading to v1.4.1 or downgrading to v1.3.2 should fix.

**Comment by nikrolls** [comment]
Thanks @jaredcbaum, I'll give this a go.

**Comment by SheepFromHeaven** [comment]
@jaredcbaum in case they are released in v2.0 we will not have the possibility to use mixins then? If this is the case, I do not see a the use of this change!

In this case please consider my proposed change/PR #44

**Comment by SheepFromHeaven** [comment]
This will make a progressive improvement instead of breaking

**Comment by jaredcbaum** [comment]
@SheepFromHeaven Thanks again for the PR, we will be testing it out soon to see how it works.

In this specific example it would have been possible to use the "includes.scss" globally by having the ```injectGlobalPaths``` set up like this:
```
sass({
    injectGlobalPaths: [
        ["src/global/includes.scss", "*"]
    ],
}),
```

The * character indicates a global namespace, otherwise you'd have to access the mixins in the file by saying doing ```@include includes.test-mixin```

**Comment by SheepFromHeaven** [comment]
@jaredcbaum thanks for the explanation there 🙂

**Comment by nikrolls** [comment]
This worked, thanks @jaredcbaum!

**Comment by jaredcbaum** [comment]
@nikrolls Of course, glad it work!

@SheepFromHeaven No problem, glad I could help.  Thank _you_ for contributing!
