### ISSUE TITLE
Build doesn't recognize the library

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/stencil-sass#5]
When I run any kind of `build` command, I get the following error:

> [ ERROR ]  style error
>            Style "src\components\app-home\app-home.scss" is a Sass file,
>            however the "sass" plugin has not been installed. Please install the
>            "@stencil/sass" plugin and add it to "config.plugins" within the
>            project's stencil.config.js file. For more info please see:
>            https://www.npmjs.com/package/@stencil/sass

I can tell you that `@stencil/sass` is in my node modules, latest version.

These are all of my dependencies:
```json
  "dependencies": {
    "@ionic/core": "^4.0.0-beta.1",
    "@stencil/core": "^0.10.10"
  },
  "devDependencies": {
    "@types/jest": "^22.2.2",
    "jest": "^22.4.3",
    "@stencil/sass": "latest"
  },
```

And this is my `stencil.config.ts`:
```ts
// https://stenciljs.com/docs/config
import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';

export const config: Config = {
  outputTargets: [
    {
      type: 'www',
      serviceWorker: {
        swSrc: 'src/sw.js'
      }
    }
  ],
  globalScript: 'src/global/app.ts',
  plugins: [
    sass({
      injectGlobalPaths: ['src/global/app.scss']
    })
  ],
};
```

**Comment by adamdbradley** [comment]
How `sass` is imported changed in stencil `0.11.0`, but looks like your version of stencil is `0.10.10`: https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-0110-2018-07-31

**Comment by AmitMY** [comment]
Thanks, I tried using the old import style, didn't work. However, updating core worked!
