### ISSUE TITLE
sass error undefined variable using injectGlobalPaths

### ISSUE THREAD

**Issue by elysium001** [ionic-team/stencil-sass#67]
I noticed that `injectGlobalPaths` stopped working after I updated to v1.5.0

I reverted to 1.4 in the meantime.

Please let me know if you need more information.

node version: `v14.16.1`
os: Mac 10.15.7

Here's what my dependencies look like:
```json
  "dependencies": {
    "@popperjs/core": "^2.9.1",
    "@stencil/angular-output-target": "0.0.6",
    "@stencil/core": "2.5.2",
    "@stencil/react-output-target": "0.0.9",
    "@stencil/vue-output-target": "^0.4.2",
    "bootstrap": "^5.1.0",
    "clipboard": "^2.0.8",
    "highlight.js": "^10.7.3",
    "html-entities": "^2.3.2",
    "marked": "^3.0.2"
  },
  "devDependencies": {
    "@stencil/postcss": "^2.0.0",
    "@stencil/sass": "1.4.1",
    "@types/autoprefixer": "^9.7.2",
    "@types/bootstrap": "^5.0.17",
    "@types/jest": "^26.0.20",
    "@types/puppeteer": "^5.4.0",
    "autoprefixer": "^10.2.1",
    "concurrently": "^6.2.1",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.3",
    "jest-cli": "^26.6.3",
    "prettier": "^2.3.0",
    "rollup": "^2.56.3",
    "rollup-plugin-copy": "^3.4.0",
    "stencil-inline-svg": "^1.0.1",
    "ts-jest": "^26.5.6"
  }
```

**Comment by kaiszybiak** [comment]
Hey @elysium001 :) I had the same issue.

**Context**:
bump @stencil/sass from 1.4.1 to 1.5.0 see changes: [v1.4.1...v1.5.0-0](https://github.com/ionic-team/stencil-sass/compare/v1.4.1...v1.5.0-0)

**Assumption:**
This [line](https://github.com/ionic-team/stencil-sass/compare/v1.4.1...v1.5.0-0#diff-3294a832ea2276e554177e0b3007cc2d401c082912c7fbde49fa09141bf1aed1R58) is wrong according to [this](https://github.com/ionic-team/stencil-sass/compare/v1.4.1...v1.5.0-0#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R38) documentation. It will always return `@use` no matter if we provide an array of type `[string, string]` or of  `string`.

**What does that mean:**
`injectGlobalPaths: [something.scss]` will result in `@use path/something;`. This again means, that the injected global paths defaults to the namespace `something` . So we would need to access the variables like this: `something.some-color.`

**Workaround:**
You can bypass this problem until it get's fixed for `v1`  by changing 
this: `injectGlobalPaths: [some-path/global.scss ],` 
to  this:`injectGlobalPaths: [[some-path/global.scss, "*"]]`

**Comment by gtranter** [comment]
I'm running into the same bug as well.

Also - the 1.5.0 update should have been 2.0.0 IMO - because it requires Stencil 2.x - that's a breaking change. We still work on some Stencil 1.x projects which have the dependency as 
```
"@stencil/sass": "^1.3.0"
```
When the project is installed, it throws the warning
```
@stencil/sass@1.5.0 requires a peer of @stencil/core@>=2.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by splitinfinities** [comment]
I'm getting started on the root issue here now.

**Comment by splitinfinities** [comment]
Encouraging to hear! Thank y'all so much for the patience! 🙇‍♂️
