### ISSUE TITLE
Unable to import partials in global directory

### ISSUE THREAD

**Issue by jacobgelman** [ionic-team/stencil-sass#7]
I have a main stylesheet, global.scss, and two partials which I would like to import into it.

![Files](https://user-images.githubusercontent.com/3182119/43793851-8f9cc288-9a31-11e8-8f01-29b7742efd32.png)

At the top of global.scss, I try to import them as I normally would using Sass:
```sass
@import "normalize";
@import "utils";
```

However, after doing this I receive the following error:
![Error](https://user-images.githubusercontent.com/3182119/43793941-c88b850c-9a31-11e8-82a3-1968100df7c7.png)

**Comment by chilipote** [comment]
Maybe a stupid question, but did you try : `@import "_normalize"` ( with the `_` ) or `@import "./_normalize"`

**Comment by jaredcbaum** [comment]
Working as of v1.4.0 (Possibly earlier).
I tested using the @use syntax which is now recommended by the sass team.

In your situation you would say:
`@use 'normalize' as '*'; `
in order to import into global namespace.
